# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.29.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.29.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jessieouyang/group3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jessieouyang/group3

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.29.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.29.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jessieouyang/group3/CMakeFiles /Users/jessieouyang/group3//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jessieouyang/group3/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named menv

# Build rule for target.
menv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 menv
.PHONY : menv

# fast build rule for target.
menv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/build
.PHONY : menv/fast

#=============================================================================
# Target rules for targets named CopyShaders

# Build rule for target.
CopyShaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CopyShaders
.PHONY : CopyShaders

# fast build rule for target.
CopyShaders/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CopyShaders.dir/build.make CMakeFiles/CopyShaders.dir/build
.PHONY : CopyShaders/fast

#=============================================================================
# Target rules for targets named doc_doxygen

# Build rule for target.
doc_doxygen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 doc_doxygen
.PHONY : doc_doxygen

# fast build rule for target.
doc_doxygen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/doc_doxygen.dir/build.make CMakeFiles/doc_doxygen.dir/build
.PHONY : doc_doxygen/fast

external/imgui/backends/imgui_impl_glfw.o: external/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : external/imgui/backends/imgui_impl_glfw.o

# target to build an object file
external/imgui/backends/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/external/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : external/imgui/backends/imgui_impl_glfw.cpp.o

external/imgui/backends/imgui_impl_glfw.i: external/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : external/imgui/backends/imgui_impl_glfw.i

# target to preprocess a source file
external/imgui/backends/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/external/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : external/imgui/backends/imgui_impl_glfw.cpp.i

external/imgui/backends/imgui_impl_glfw.s: external/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : external/imgui/backends/imgui_impl_glfw.s

# target to generate assembly for a file
external/imgui/backends/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/external/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : external/imgui/backends/imgui_impl_glfw.cpp.s

external/imgui/backends/imgui_impl_opengl3.o: external/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : external/imgui/backends/imgui_impl_opengl3.o

# target to build an object file
external/imgui/backends/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/external/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : external/imgui/backends/imgui_impl_opengl3.cpp.o

external/imgui/backends/imgui_impl_opengl3.i: external/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : external/imgui/backends/imgui_impl_opengl3.i

# target to preprocess a source file
external/imgui/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/external/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : external/imgui/backends/imgui_impl_opengl3.cpp.i

external/imgui/backends/imgui_impl_opengl3.s: external/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : external/imgui/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
external/imgui/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/external/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : external/imgui/backends/imgui_impl_opengl3.cpp.s

external/imgui/imgui.o: external/imgui/imgui.cpp.o
.PHONY : external/imgui/imgui.o

# target to build an object file
external/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/external/imgui/imgui.cpp.o
.PHONY : external/imgui/imgui.cpp.o

external/imgui/imgui.i: external/imgui/imgui.cpp.i
.PHONY : external/imgui/imgui.i

# target to preprocess a source file
external/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/external/imgui/imgui.cpp.i
.PHONY : external/imgui/imgui.cpp.i

external/imgui/imgui.s: external/imgui/imgui.cpp.s
.PHONY : external/imgui/imgui.s

# target to generate assembly for a file
external/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/external/imgui/imgui.cpp.s
.PHONY : external/imgui/imgui.cpp.s

external/imgui/imgui_demo.o: external/imgui/imgui_demo.cpp.o
.PHONY : external/imgui/imgui_demo.o

# target to build an object file
external/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/external/imgui/imgui_demo.cpp.o
.PHONY : external/imgui/imgui_demo.cpp.o

external/imgui/imgui_demo.i: external/imgui/imgui_demo.cpp.i
.PHONY : external/imgui/imgui_demo.i

# target to preprocess a source file
external/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/external/imgui/imgui_demo.cpp.i
.PHONY : external/imgui/imgui_demo.cpp.i

external/imgui/imgui_demo.s: external/imgui/imgui_demo.cpp.s
.PHONY : external/imgui/imgui_demo.s

# target to generate assembly for a file
external/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/external/imgui/imgui_demo.cpp.s
.PHONY : external/imgui/imgui_demo.cpp.s

external/imgui/imgui_draw.o: external/imgui/imgui_draw.cpp.o
.PHONY : external/imgui/imgui_draw.o

# target to build an object file
external/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/external/imgui/imgui_draw.cpp.o
.PHONY : external/imgui/imgui_draw.cpp.o

external/imgui/imgui_draw.i: external/imgui/imgui_draw.cpp.i
.PHONY : external/imgui/imgui_draw.i

# target to preprocess a source file
external/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/external/imgui/imgui_draw.cpp.i
.PHONY : external/imgui/imgui_draw.cpp.i

external/imgui/imgui_draw.s: external/imgui/imgui_draw.cpp.s
.PHONY : external/imgui/imgui_draw.s

# target to generate assembly for a file
external/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/external/imgui/imgui_draw.cpp.s
.PHONY : external/imgui/imgui_draw.cpp.s

external/imgui/imgui_tables.o: external/imgui/imgui_tables.cpp.o
.PHONY : external/imgui/imgui_tables.o

# target to build an object file
external/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/external/imgui/imgui_tables.cpp.o
.PHONY : external/imgui/imgui_tables.cpp.o

external/imgui/imgui_tables.i: external/imgui/imgui_tables.cpp.i
.PHONY : external/imgui/imgui_tables.i

# target to preprocess a source file
external/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/external/imgui/imgui_tables.cpp.i
.PHONY : external/imgui/imgui_tables.cpp.i

external/imgui/imgui_tables.s: external/imgui/imgui_tables.cpp.s
.PHONY : external/imgui/imgui_tables.s

# target to generate assembly for a file
external/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/external/imgui/imgui_tables.cpp.s
.PHONY : external/imgui/imgui_tables.cpp.s

external/imgui/imgui_widgets.o: external/imgui/imgui_widgets.cpp.o
.PHONY : external/imgui/imgui_widgets.o

# target to build an object file
external/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/external/imgui/imgui_widgets.cpp.o
.PHONY : external/imgui/imgui_widgets.cpp.o

external/imgui/imgui_widgets.i: external/imgui/imgui_widgets.cpp.i
.PHONY : external/imgui/imgui_widgets.i

# target to preprocess a source file
external/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/external/imgui/imgui_widgets.cpp.i
.PHONY : external/imgui/imgui_widgets.cpp.i

external/imgui/imgui_widgets.s: external/imgui/imgui_widgets.cpp.s
.PHONY : external/imgui/imgui_widgets.s

# target to generate assembly for a file
external/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/external/imgui/imgui_widgets.cpp.s
.PHONY : external/imgui/imgui_widgets.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/main.cpp.s
.PHONY : main.cpp.s

minigame/minigame.o: minigame/minigame.cpp.o
.PHONY : minigame/minigame.o

# target to build an object file
minigame/minigame.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/minigame/minigame.cpp.o
.PHONY : minigame/minigame.cpp.o

minigame/minigame.i: minigame/minigame.cpp.i
.PHONY : minigame/minigame.i

# target to preprocess a source file
minigame/minigame.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/minigame/minigame.cpp.i
.PHONY : minigame/minigame.cpp.i

minigame/minigame.s: minigame/minigame.cpp.s
.PHONY : minigame/minigame.s

# target to generate assembly for a file
minigame/minigame.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/minigame/minigame.cpp.s
.PHONY : minigame/minigame.cpp.s

minigame/src/character.o: minigame/src/character.cpp.o
.PHONY : minigame/src/character.o

# target to build an object file
minigame/src/character.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/minigame/src/character.cpp.o
.PHONY : minigame/src/character.cpp.o

minigame/src/character.i: minigame/src/character.cpp.i
.PHONY : minigame/src/character.i

# target to preprocess a source file
minigame/src/character.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/minigame/src/character.cpp.i
.PHONY : minigame/src/character.cpp.i

minigame/src/character.s: minigame/src/character.cpp.s
.PHONY : minigame/src/character.s

# target to generate assembly for a file
minigame/src/character.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/minigame/src/character.cpp.s
.PHONY : minigame/src/character.cpp.s

minigame/src/platform.o: minigame/src/platform.cpp.o
.PHONY : minigame/src/platform.o

# target to build an object file
minigame/src/platform.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/minigame/src/platform.cpp.o
.PHONY : minigame/src/platform.cpp.o

minigame/src/platform.i: minigame/src/platform.cpp.i
.PHONY : minigame/src/platform.i

# target to preprocess a source file
minigame/src/platform.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/minigame/src/platform.cpp.i
.PHONY : minigame/src/platform.cpp.i

minigame/src/platform.s: minigame/src/platform.cpp.s
.PHONY : minigame/src/platform.s

# target to generate assembly for a file
minigame/src/platform.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/minigame/src/platform.cpp.s
.PHONY : minigame/src/platform.cpp.s

minigame/src/stb_image_impl.o: minigame/src/stb_image_impl.cpp.o
.PHONY : minigame/src/stb_image_impl.o

# target to build an object file
minigame/src/stb_image_impl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/minigame/src/stb_image_impl.cpp.o
.PHONY : minigame/src/stb_image_impl.cpp.o

minigame/src/stb_image_impl.i: minigame/src/stb_image_impl.cpp.i
.PHONY : minigame/src/stb_image_impl.i

# target to preprocess a source file
minigame/src/stb_image_impl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/minigame/src/stb_image_impl.cpp.i
.PHONY : minigame/src/stb_image_impl.cpp.i

minigame/src/stb_image_impl.s: minigame/src/stb_image_impl.cpp.s
.PHONY : minigame/src/stb_image_impl.s

# target to generate assembly for a file
minigame/src/stb_image_impl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/minigame/src/stb_image_impl.cpp.s
.PHONY : minigame/src/stb_image_impl.cpp.s

minigame/src/window.o: minigame/src/window.cpp.o
.PHONY : minigame/src/window.o

# target to build an object file
minigame/src/window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/minigame/src/window.cpp.o
.PHONY : minigame/src/window.cpp.o

minigame/src/window.i: minigame/src/window.cpp.i
.PHONY : minigame/src/window.i

# target to preprocess a source file
minigame/src/window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/minigame/src/window.cpp.i
.PHONY : minigame/src/window.cpp.i

minigame/src/window.s: minigame/src/window.cpp.s
.PHONY : minigame/src/window.s

# target to generate assembly for a file
minigame/src/window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/minigame/src/window.cpp.s
.PHONY : minigame/src/window.cpp.s

src/Camera.o: src/Camera.cpp.o
.PHONY : src/Camera.o

# target to build an object file
src/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/src/Camera.cpp.o
.PHONY : src/Camera.cpp.o

src/Camera.i: src/Camera.cpp.i
.PHONY : src/Camera.i

# target to preprocess a source file
src/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/src/Camera.cpp.i
.PHONY : src/Camera.cpp.i

src/Camera.s: src/Camera.cpp.s
.PHONY : src/Camera.s

# target to generate assembly for a file
src/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/src/Camera.cpp.s
.PHONY : src/Camera.cpp.s

src/Cube.o: src/Cube.cpp.o
.PHONY : src/Cube.o

# target to build an object file
src/Cube.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/src/Cube.cpp.o
.PHONY : src/Cube.cpp.o

src/Cube.i: src/Cube.cpp.i
.PHONY : src/Cube.i

# target to preprocess a source file
src/Cube.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/src/Cube.cpp.i
.PHONY : src/Cube.cpp.i

src/Cube.s: src/Cube.cpp.s
.PHONY : src/Cube.s

# target to generate assembly for a file
src/Cube.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/src/Cube.cpp.s
.PHONY : src/Cube.cpp.s

src/Shader.o: src/Shader.cpp.o
.PHONY : src/Shader.o

# target to build an object file
src/Shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/src/Shader.cpp.o
.PHONY : src/Shader.cpp.o

src/Shader.i: src/Shader.cpp.i
.PHONY : src/Shader.i

# target to preprocess a source file
src/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/src/Shader.cpp.i
.PHONY : src/Shader.cpp.i

src/Shader.s: src/Shader.cpp.s
.PHONY : src/Shader.s

# target to generate assembly for a file
src/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/src/Shader.cpp.s
.PHONY : src/Shader.cpp.s

src/Tokenizer.o: src/Tokenizer.cpp.o
.PHONY : src/Tokenizer.o

# target to build an object file
src/Tokenizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/src/Tokenizer.cpp.o
.PHONY : src/Tokenizer.cpp.o

src/Tokenizer.i: src/Tokenizer.cpp.i
.PHONY : src/Tokenizer.i

# target to preprocess a source file
src/Tokenizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/src/Tokenizer.cpp.i
.PHONY : src/Tokenizer.cpp.i

src/Tokenizer.s: src/Tokenizer.cpp.s
.PHONY : src/Tokenizer.s

# target to generate assembly for a file
src/Tokenizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/src/Tokenizer.cpp.s
.PHONY : src/Tokenizer.cpp.s

src/Window.o: src/Window.cpp.o
.PHONY : src/Window.o

# target to build an object file
src/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/src/Window.cpp.o
.PHONY : src/Window.cpp.o

src/Window.i: src/Window.cpp.i
.PHONY : src/Window.i

# target to preprocess a source file
src/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/src/Window.cpp.i
.PHONY : src/Window.cpp.i

src/Window.s: src/Window.cpp.s
.PHONY : src/Window.s

# target to generate assembly for a file
src/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menv.dir/build.make CMakeFiles/menv.dir/src/Window.cpp.s
.PHONY : src/Window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CopyShaders"
	@echo "... doc_doxygen"
	@echo "... menv"
	@echo "... external/imgui/backends/imgui_impl_glfw.o"
	@echo "... external/imgui/backends/imgui_impl_glfw.i"
	@echo "... external/imgui/backends/imgui_impl_glfw.s"
	@echo "... external/imgui/backends/imgui_impl_opengl3.o"
	@echo "... external/imgui/backends/imgui_impl_opengl3.i"
	@echo "... external/imgui/backends/imgui_impl_opengl3.s"
	@echo "... external/imgui/imgui.o"
	@echo "... external/imgui/imgui.i"
	@echo "... external/imgui/imgui.s"
	@echo "... external/imgui/imgui_demo.o"
	@echo "... external/imgui/imgui_demo.i"
	@echo "... external/imgui/imgui_demo.s"
	@echo "... external/imgui/imgui_draw.o"
	@echo "... external/imgui/imgui_draw.i"
	@echo "... external/imgui/imgui_draw.s"
	@echo "... external/imgui/imgui_tables.o"
	@echo "... external/imgui/imgui_tables.i"
	@echo "... external/imgui/imgui_tables.s"
	@echo "... external/imgui/imgui_widgets.o"
	@echo "... external/imgui/imgui_widgets.i"
	@echo "... external/imgui/imgui_widgets.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... minigame/minigame.o"
	@echo "... minigame/minigame.i"
	@echo "... minigame/minigame.s"
	@echo "... minigame/src/character.o"
	@echo "... minigame/src/character.i"
	@echo "... minigame/src/character.s"
	@echo "... minigame/src/platform.o"
	@echo "... minigame/src/platform.i"
	@echo "... minigame/src/platform.s"
	@echo "... minigame/src/stb_image_impl.o"
	@echo "... minigame/src/stb_image_impl.i"
	@echo "... minigame/src/stb_image_impl.s"
	@echo "... minigame/src/window.o"
	@echo "... minigame/src/window.i"
	@echo "... minigame/src/window.s"
	@echo "... src/Camera.o"
	@echo "... src/Camera.i"
	@echo "... src/Camera.s"
	@echo "... src/Cube.o"
	@echo "... src/Cube.i"
	@echo "... src/Cube.s"
	@echo "... src/Shader.o"
	@echo "... src/Shader.i"
	@echo "... src/Shader.s"
	@echo "... src/Tokenizer.o"
	@echo "... src/Tokenizer.i"
	@echo "... src/Tokenizer.s"
	@echo "... src/Window.o"
	@echo "... src/Window.i"
	@echo "... src/Window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

